"""updated otp table

Revision ID: c667e381fcb2
Revises: bd73113a92ce
Create Date: 2026-03-18 18:06:11.078020

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c667e381fcb2'
down_revision: Union[str, None] = 'bd73113a92ce'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('revoked_tokens',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('jti', sa.String(length=255), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_revoked_tokens_jti'), 'revoked_tokens', ['jti'], unique=True)
    op.add_column('user_otp_verifications', sa.Column('active', sa.Boolean(), nullable=False))
    op.add_column('user_otp_verifications', sa.Column('attempt_count', sa.Integer(), nullable=False))
    op.add_column('user_otp_verifications', sa.Column('max_attempts', sa.Integer(), nullable=False))
    op.add_column('user_otp_verifications', sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('users', sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'last_login_at')
    op.drop_column('user_otp_verifications', 'verified_at')
    op.drop_column('user_otp_verifications', 'max_attempts')
    op.drop_column('user_otp_verifications', 'attempt_count')
    op.drop_column('user_otp_verifications', 'active')
    op.drop_index(op.f('ix_revoked_tokens_jti'), table_name='revoked_tokens')
    op.drop_table('revoked_tokens')
    # ### end Alembic commands ###
